yamlCopy code
nsg_config:
  name: main-nsg
  location: eastus
  resource_group_name: pulumi-resources
  security_rules:
    - name: allow-http
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "80"
      source_address_prefix: "*"
      destination_address_prefix: "*"
    - name: allow-https
      priority: 110
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "443"
      source_address_prefix: "*"
      destination_address_prefix: "*"

