storage_account: # configuration for storage
  name: sa
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a # these work, just hard coded resource group name
  location: southcentralus
  account_tier: Standard
  replication_type: LRS
  outputs: ""

keyvault: # configuration for keyvault
  resource_name: vault
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  location: southcentralus
  sku_name: STANDARD
  tenant_id: 12345678-1234-5678-1234-567812345678

  access_policies:
    - tenant_id: 12345678-1234-5678-1234-567812345678
      object_id: 87654321-4321-8765-4321-876543218765
      permissions:
        keys: ["get", "list", "create", "delete"]
        secrets: ["get", "list", "set", "delete"]
  outputs: ""

nsg_config: # configuration for the security layer
  name: main-nsg
  location: southcentralus
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  security_rules:
    - name: allow-http
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "80"
      source_address_prefix: "*"
      destination_address_prefix: "*"
    - name: allow-https
      priority: 110
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "443"
      source_address_prefix: "*"
      destination_address_prefix: "*"
