
storage_account: # configuration for storage, might have to alter this, there is more than one different kind of sa
  lakehouse:
     account_name: salakehouse
     resource_group_name: rg-ac-cus-adb-acclrtor
     location: southcentralus
     container_name: lk-cont
     blob_name: blob-lakehouse
     private_endpoint_name: pe-conn
     account_tier: Standard
     replication_type: LRS
  landing_zone:
     account_name: salz
     resource_group_name: rg-ac-cus-adb-acclrtor
     location: southcentralus
     container_name: lz-cont
     blob_name: blob-lz
     private_endpoint_name: pe-conn
     local_user_name: localuserlz
     account_tier: Standard
     replication_type: LRS


keyvault: # configuration for keyvault, gonna have to change as well
  resource_name: vault
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  location: southcentralus
  sku_name: STANDARD
  tenant_id: 12345678-1234-5678-1234-567812345678
  access_policies:
    - tenant_id: 12345678-1234-5678-1234-567812345678
      object_id: 87654321-4321-8765-4321-876543218765
      permissions:
        keys: ["get", "list", "create", "delete"]
        secrets: ["get", "list", "set", "delete"]
  outputs: ""

nsg_config: # configuration for the security layer, here for now, gonna have to alter to change the architecture
  name: main-nsg
  location: southcentralus
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  security_rules:
    - name: allow-http
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "80"
      source_address_prefix: "*"
      destination_address_prefix: "*"
    - name: allow-https
      priority: 110
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "443"
      source_address_prefix: "*"
      destination_address_prefix: "*"

bastion_host:
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  name: bastion-host
  location: southcentralus
  ip_config_name:
  subnet_id:
  public_ip_address_id:


vnet:
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  name: vnet-demo-databricks
  location: southcentralus
  address_prefix: 172.16.0.0/16
  subnets:
    - resource_name: subnet
      name: default
      address_prefix: 172.16.0.0/24
    - resource_name: subnet
      name: AzureBastionSubnet
      address_prefix: 172.16.0.0/24
    - resource_name: subnet
      name: subnet-key-vault
      address_prefix: 172.16.3.0/24
    - resource_name: subnet
      name: subnet-lakehouse
      address_prefix: 172.16.2.0/24
    - resource_name: subnet
      name: databricks-workspace
      address_prefix:
    - resource_name: subnet
      name: public_subnet
      address_prefix: 172.16.4.0/24
    - resource_name: subnet
      name: private-subnet
      address_prefix: 172.16.5.0/2



adb: # don't know if this is right
  $schema: ""
  contentVersion: ""
  parameters:
    workspaces_name:
      defaultValue: ""
      type: ""
    externalid:
      defaultValue: ""
      type: "String"
  variables: {}
  resources:
    - type: ""
      apiVersion: ""
      name: ""
      location: ""
      tags:
        environment: ""
      sku:
        name: ""
      properties:
        defaultCatalog:
          initialType: ""
        publicNetworkAccess: ""
        requiredNsgRules: ""
        managedResourceGroupId: ""
        parameters:
          customPrivateSubnetName:
            value: ""
          customPublicSubnetName:
            value: ""
          customVirtualNetworkId:
            value: ""
          enableNoPublicIp:
            value: ""
          prepareEncryption:
            value: ""
          publicIpName:
            value: ""
          requireInfrastructureEncryption:
            value: ""
          storageAccountName:
            value: ""
          storageAccountSkuName:
            value: ""
          vnetAddressPrefix:
            value: ""
        authorizations:
          - principalId: ""
            roleDefinitionId: ""
        createdBy: {}
        updatedBy: {}
    - type: "Microsoft.Databricks/workspaces/privateEndpointConnections"
      apiVersion: "2023-09-15-preview"
      name: ""
      dependsOn:
        - ""
      properties:
        privateEndpoint: {}
        groupIds:
          - ""
        privateLinkServiceConnectionState:
          status: ""
          description: ""
          actionsRequired: ""
    - type: "Microsoft.Databricks/workspaces/privateEndpointConnections"
      apiVersion: "2023-09-15-preview"
      name: ""
      dependsOn:
        - ""
      properties:
        privateEndpoint: {}
        groupIds:
          - ""
        privateLinkServiceConnectionState:
          status: ""
          description: ""
          actionsRequired: ""

virtual_machine:
  resource_group_name: myResourceGroup # change this
  location: southcentralus
  vm_name: myVM
  user: your-username
  pw: your-password
  network_interface_id: /subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkInterfaces/{existing-nic-name}
  os_computer_name: myVM
  os_disk_name: myVMosdisk
