storage_account: # configuration for storage, might have to alter this, there is more than one different kind of sa
  name: sa
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a # these work, just hard coded resource group name
  location: southcentralus
  account_tier: Standard
  replication_type: LRS
  outputs: ""

keyvault: # configuration for keyvault, gonna have to change as well
  resource_name: vault
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  location: southcentralus
  sku_name: STANDARD
  tenant_id: 12345678-1234-5678-1234-567812345678

  access_policies:
    - tenant_id: 12345678-1234-5678-1234-567812345678
      object_id: 87654321-4321-8765-4321-876543218765
      permissions:
        keys: ["get", "list", "create", "delete"]
        secrets: ["get", "list", "set", "delete"]
  outputs: ""

nsg_config: # configuration for the security layer, here for now, gonna have to alter to change the architecture
  name: main-nsg
  location: southcentralus
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  security_rules:
    - name: allow-http
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "80"
      source_address_prefix: "*"
      destination_address_prefix: "*"
    - name: allow-https
      priority: 110
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "443"
      source_address_prefix: "*"
      destination_address_prefix: "*"

data_factory: # don't know if this is correct yet, just putting this there
  resource_group_name:
  identity:
  location:
  customer_managed_key_id:
  name:
  public_network_enabled:
  tags:

bastion_host:
  resource_group_name:
  name:
  location:
  ip_configuration:
    - name:
      subnet_id:
      public_ip_address_name:

data_lake:
  storage_account_id:
  aces:
  default_encryption_scope:
  group:
  name:
  owner:
  properties:

vnet:
  resource_group_name: rg-ac-cus-adb-acclrtor00ebbb6a
  name: vnet-demo-databricks
  location:
  address_space: #172.-------
  subnets:
    - name: #default
      address_prefix: #172.----
    - name: #azurebastionsubnet
      address_prefix:
    - name: #subnet-keyvault
      address_prefix:
    - name: #subnet-lakehouse
      address_prefix:
    - name: # databricks-workspace
      address_prefix:
    - name: #public_subnet
      address_prefix:
    - name: #private-subnet
      address_prefix:



adb:
  $schema: ""
  contentVersion: ""
  parameters:
    workspaces_name:
      defaultValue: ""
      type: ""
    externalid:
      defaultValue: ""
      type: "String"
  variables: {}
  resources:
    - type: ""
      apiVersion: ""
      name: ""
      location: ""
      tags:
        environment: ""
      sku:
        name: ""
      properties:
        defaultCatalog:
          initialType: ""
        publicNetworkAccess: ""
        requiredNsgRules: ""
        managedResourceGroupId: ""
        parameters:
          customPrivateSubnetName:
            value: ""
          customPublicSubnetName:
            value: ""
          customVirtualNetworkId:
            value: ""
          enableNoPublicIp:
            value: ""
          prepareEncryption:
            value: ""
          publicIpName:
            value: ""
          requireInfrastructureEncryption:
            value: ""
          storageAccountName:
            value: ""
          storageAccountSkuName:
            value: ""
          vnetAddressPrefix:
            value: ""
        authorizations:
          - principalId: ""
            roleDefinitionId: ""
        createdBy: {}
        updatedBy: {}
    - type: "Microsoft.Databricks/workspaces/privateEndpointConnections"
      apiVersion: "2023-09-15-preview"
      name: ""
      dependsOn:
        - ""
      properties:
        privateEndpoint: {}
        groupIds:
          - ""
        privateLinkServiceConnectionState:
          status: ""
          description: ""
          actionsRequired: ""
    - type: "Microsoft.Databricks/workspaces/privateEndpointConnections"
      apiVersion: "2023-09-15-preview"
      name: ""
      dependsOn:
        - ""
      properties:
        privateEndpoint: {}
        groupIds:
          - ""
        privateLinkServiceConnectionState:
          status: ""
          description: ""
          actionsRequired: ""
