
storage_account: # configuration for storage, might have to alter this, there is more than one different kind of sa
  lakehouse:
     account_name: salakehouse
     resource_group_name: rg-ac-cus-adb-acclrtor
     location: southcentralus
     container_name: lk-cont
     blob_name: blob-lakehouse
     private_endpoint_name: pe-lakehouse
     private_link_name: pl-service-name-lk
     dfs_private_endpoint_name: pe-lakehouse-dfs
     dfs_private_link_name: dfs-pl-name-lk
     subnet_id: /subscriptions/7e1258ee-836d-4df2-85bd-8c7e91d059f9/resourceGroups/rg-ac-cus-adb-acclrtor/providers/Microsoft.Network/virtualNetworks/vnet-demo-databricks/subnets/subnet-lakehouse
     account_tier: Standard
     replication_type: LRS
  landing_zone:
     account_name: salz
     resource_group_name: rg-ac-cus-adb-acclrtor
     location: southcentralus
     container_name: lz-cont
     blob_name: blob-lz
     private_endpoint_name: pe-conn-2
     private_link_name: pl-service-name-lz
     dfs_private_endpoint_name: pe-lz-dfs
     dfs_private_link_name: dfs-pl-name-lz
     subnet_id: /subscriptions/7e1258ee-836d-4df2-85bd-8c7e91d059f9/resourceGroups/rg-ac-cus-adb-acclrtor/providers/Microsoft.Network/virtualNetworks/vnet-demo-databricks/subnets/subnet-sftp-landingzone
     local_user_name: localuserlz
     account_tier: Standard
     replication_type: LRS


keyvault: # configuration for keyvault, gonna have to change as well
  resource_name: vault
  resource_group_name: rg-ac-cus-adb-acclrtor
  location: southcentralus
  sku_name: STANDARD
  tenant_id: 12345678-1234-5678-1234-567812345678
  access_policies:
    - tenant_id: 12345678-1234-5678-1234-567812345678
      object_id: 87654321-4321-8765-4321-876543218765
      permissions:
        keys: ["get", "list", "create", "delete"]
        secrets: ["get", "list", "set", "delete"]
  subnet_id: /subscriptions/7e1258ee-836d-4df2-85bd-8c7e91d059f9/resourceGroups/rg-ac-cus-adb-acclrtor/providers/Microsoft.Network/virtualNetworks/vnet-demo-databricks/subnets/subnet-key-vault


nsg_config: # configuration for the security layer, here for now, gonna have to alter to change the architecture
  name: main-nsg
  location: southcentralus
  resource_group_name: rg-ac-cus-adb-acclrtor
  security_rules:
    - name: AllowVnetInbound
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "*"
      source_address_prefix: 172.16.0.0/16
      destination_address_prefix: "*"
    - name: AllowAzureLoadBalancer
      priority: 101
      direction: Inbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "*"
      source_address_prefix: "AzureLoadBalancer"
      destination_address_prefix: "*"
    - name: DenyAllInbound
      priority: 102
      direction: Inbound
      access: Deny
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "*"
      source_address_prefix: "*"
      destination_address_prefix: "*"
    - name: AllowVnetOutbound
      priority: 100
      direction: Outbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "*"
      source_address_prefix: "*"
      destination_address_prefix: 172.16.0.0/16
    - name: AllowInternetOutbound
      priority: 101
      direction: Outbound
      access: Allow
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "*"
      source_address_prefix: "*"
      destination_address_prefix: "Internet"
    - name: DenyAllOutbound
      priority: 102
      direction: Outbound
      access: Deny
      protocol: Tcp
      source_port_range: "*"
      destination_port_range: "*"
      source_address_prefix: "*"
      destination_address_prefix: "*"


bastion_host:
  resource_group_name: rg-ac-cus-adb-acclrtor
  name: bastion-host
  location: southcentralus
  ip_config_name: bastionIPConfig
  subnet_id: /subscriptions/7e1258ee-836d-4df2-85bd-8c7e91d059f9/resourceGroups/rg-ac-cus-adb-acclrtor/providers/Microsoft.Network/virtualNetworks/vnet-demo-databricks/subnets/AzureBastionSubnet
  public_ip_address_name: pulumiPublicIP


vnet:
  resource_group_name: rg-ac-cus-adb-acclrtor
  name: vnet-demo-databricks
  location: southcentralus
  address_prefix: 172.16.0.0/16
  subnets:
    - resource_name: subnet
      name: default
      address_prefix: 172.16.8.0/24
    - resource_name: subnet
      name: AzureBastionSubnet
      address_prefix: 172.16.6.0/24
    - resource_name: subnet
      name: subnet-key-vault
      address_prefix: 172.16.7.0/24
    - resource_name: subnet
      name: subnet-lakehouse
      address_prefix: 172.16.11.0/24
    - resource_name: subnet
      name: databricks-workspace
      address_prefix: 172.16.1.0/24
    - resource_name: subnet
      name: subnet-sftp-landingzone
      address_prefix: 172.16.9.0/24



adb:
  resource_group_name: rg-ac-cus-adb-acclrtor
  location: southcentralus
  lakehouse_access_connector_name: lk-access-connector
  landing_zone_access_connector_name:  lz-access-connector
  workspace_name: adb-workspace
  private_subnet_name: private-subnet
  public_subnet_name: public-subnet
  subnet_id: /subscriptions/7e1258ee-836d-4df2-85bd-8c7e91d059f9/resourceGroups/rg-ac-cus-adb-acclrtor/providers/Microsoft.Network/virtualNetworks/vnet-demo-databricks/subnets/databricks-workspace





virtual_machine:
  resource_group_name: rg-ac-cus-adb-acclrtor # change this
  location: southcentralus
  vm_name: vm-adb-dl
  user: your-username
  pw: Light House High Waves
  network_interface_name: vm-adb-dl-nic
  subnet_id: /subscriptions/7e1258ee-836d-4df2-85bd-8c7e91d059f9/resourceGroups/rg-ac-cus-adb-acclrtor/providers/Microsoft.Network/virtualNetworks/vnet-demo-databricks/subnets/default
  os_computer_name: myVM
  os_disk_name: myVMosdisk
